### ISSUE TITLE
Templates not included

### ISSUE THREAD

**Issue by NotSqrt** [getsentry/sentry-auth-google#2]
Hello,

This project needs a MANIFEST.in to declare the inclusion of html files..

Thanks,

**Comment by mattrobenolt** [comment]
A `MANIFEST.in` file is only needed for an `sdist` bundle, which we don't do since we recommend installing from source.

Were you hitting an issue with this not existing some how?

**Comment by dcramer** [comment]
We might still need the manifest. Either way should add it. 






On Wed, Sep 30, 2015 at 9:28 AM -0700, "Matt Robenolt" <notifications@github.com> wrote:












A MANIFEST.in file is only needed for an sdist bundle, which we don't do since we recommend installing from source.



Were you hitting an issue with this not existing some how?

**Comment by NotSqrt** [comment]
I did ``pip install https://github.com/getsentry/sentry-auth-google/archive/master.zip``, and the templates were not installed (pip version 7.1.0).

**Comment by mattrobenolt** [comment]
Ah, if you threw a `-e` in front of that it would. :) But that's fair, we'll fix it up. Thanks for the feedback.

**Comment by NotSqrt** [comment]
Yay!

@dcramer Is provider authentication supposed to work yet ?
I tested this morning, but in https://github.com/getsentry/sentry/blob/b212b1386666bcf9e1ca97f9ced3a273d9e6c3b7/src/sentry/templates/sentry/organization-login.html#L19 , the ``btn-login-{{ provider_key }}`` button doesn't do anything..

**Comment by dcramer** [comment]
@NotSqrt you're using the latest version of Sentry?

**Comment by NotSqrt** [comment]
I tried the current master, yes :smile:
