### ISSUE TITLE
Cannot import name MigratingIdentityID

### ISSUE THREAD

**Issue by BenCoffeed** [getsentry/sentry-auth-google#21]
While trying to run the initial `upgrade` command to initialize my on-premise cluster, I get the following error when Google Auth is enabled(full log available on request):

```
django.core.exceptions.ImproperlyConfigured: ImportError sentry_auth_google: cannot import name MigratingIdentityId
```
It looks like this may relate to #20 

## Steps to reproduce:
1. Clone [Sentry On-Premise repo](https://github.com/getsentry/onpremise)
2. `cd onpremise && echo https://github.com/getsentry/sentry-auth-google/archive/master.zip >> requirements.txt` 
3. Follow setup instructions referenced in README.txt to generate Google Auth Client ID and Client Secret.
4. Modify onpremise/sentry.conf.py to include the following lines replacing items in <> with the values generated in step 3:
  ```
  SENTRY_FEATURES['organizations:sso'] = True
  GOOGLE_CLIENT_ID = <yourid>.apps.googleusercontent.com
  GOOGLE_CLIENT_SECRET = <yourGoogleSecret>
  ```
3. Follow [On-premise Docker installation instructions](https://docs.sentry.io/server/installation/docker/).

**NOTE**: I see this particular error message while [running migrations](https://docs.sentry.io/server/installation/docker/#running-migrations)

## Setup
* getsentry/onnpremise branch: master 
* Sentry version: 8.22
* Docker version: 17.09.0-ce, build afdb6d4
* Docker Host OS: Ubuntu 16.04

**Comment by dcramer** [comment]
You should pin your version of sentry-auth-google to a previous SHA, or you will also need to run sentry master to be compatible.

**Comment by BenCoffeed** [comment]
Figured as much. Thanks for the prompt reply @dcramer . Sorry for any noise. Hopefully it will help other unassuming on-prem. folks.

**Comment by mattrobenolt** [comment]
Yeah, unfortuantely, we started actively developing this again and we haven't tagged released. I'm trying to figure out what we'll want to do moving forward. Either version identically to how we do `sentry-plugins` and always release them together, so like, `sentry==8.22.0` would also work with `sentry-auth-github==8.22.0`, etc. Or we roll `sentry-auth-*` into `sentry-plugins` since I don't see a ton of value in keeping them separate.

But as of right now, I don't have a better answer except pinning to a version that works.
