### ISSUE TITLE
RFC: Support Multiple Domains

### ISSUE THREAD

**Issue by mitsuhiko** [getsentry/sentry-auth-google#7]
Currently we only support a single domain for google apps but the request came up to allow multiple domains. We should figure out if this is possible without problems and if yes, if we want to support it.

**Comment by dcramer** [comment]
we could support it better now that we're not using the Google+ support

**Comment by sbadia** [comment]
Hi here! Any update on this subject? This feature would be awesome! (my sentry is hosted on an internal domain `sentry.domain.internal`, and my google oauth provider resolv on my public domain `domain.com`, therefore OAuth doesn't work :( )

**Comment by sbadia** [comment]
* https://github.com/rogerhu/sentry-auth-google/commit/ad8101f6f04c40797c9cdb43d58626bb0346d1e5
* https://github.com/collectivehealth/sentry-auth-google/commit/72dc92cc3e5fcee1f050028b882265d79309bc5a

**Comment by dcramer** [comment]
I'm not sure this is actually needed with the recent fixed/reverts. We should once again be using Google Apps "Hosted Domain" param correctly rather than simply using the email address.

Please reopen if that's not correct and this RFC is truly for multiple Google Apps accounts.

Alternatively is this is primarily for "how to auth with OAuth" I dont know that its overly related to Google itself, and sounds like an issue with how requests are proxied to Sentry.
